name: This

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      run-id: ${{ steps.set-run-id.outputs.run-id }}
    steps:
      - name: Generate Run ID
        id: set-run-id
        run: |
          run_id=$(uuidgen)
          echo "run-id=${run_id}" >> $GITHUB_OUTPUT

  run-jobs:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        jobname: [JobA, JobB, JobC]
    outputs:
      job-log: ${{ steps.log.outputs.log }}
    steps:
      - name: Run ${{ matrix.jobname }}
        id: log
        run: |
          msg="${{ matrix.jobname }} running with RunID=${{ needs.prepare.outputs.run-id }}"
          echo "$msg"
          echo "log=$msg" >> $GITHUB_OUTPUT

  integration:
    runs-on: ubuntu-latest
    needs: run-jobs
    steps:
      - name: Combine results
        run: |
          echo '${{ toJSON(needs.run-jobs.outputs) }}'
          logs=$(echo '${{ toJSON(needs.run-jobs.outputs) }}' | jq -r '.[]."job-log"')
          echo "$logs" > combined.txt
          echo "Integration complete"
          cat combined.txt

  deploy:
    # Was not quite sure if it will be better to leave it as separate job or move to integration.
    # Left here for a while
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - name: Deploy step
        run: |
          echo "Deploy step using combined results:"
          cat combined.txt
