name: This

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      run-id: ${{ steps.set-run-id.outputs.run-id }}
    steps:
      - name: Generate Run ID
        id: set-run-id
        run: |
          run_id=$(uuidgen)
          echo "run-id=${run_id}" >> $GITHUB_OUTPUT

  run-jobs:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      fail-fast: true
      matrix:
        jobname: [JobA, JobB, JobC]
    steps:
      - name: Run ${{ matrix.jobname }}
        run: |
          echo "${{ matrix.jobname }} running with RunID=${{ needs.prepare.outputs.run-id }}" > ${{ matrix.jobname }}.log

      - name: Upload logs for ${{ matrix.jobname }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.jobname }}-log
          path: ${{ matrix.jobname }}.log

  integration:
    # Deploy stage was removed as it was doing pretty much same as integration.
    # Could be returned in case
    runs-on: ubuntu-latest
    needs: run-jobs
    steps:
      - name: Download all job logs
        uses: actions/download-artifact@v4
        with:
          pattern: "*-log"
          merge-multiple: true

      - name: Combine logs
        run: |
          cat Job*.log > combined.txt
          echo "Integration complete"
          cat combined.txt

      - name: Upload combined log
        uses: actions/upload-artifact@v4
        with:
          name: integration-log
          path: combined.txt
